language: go

go:
  - 1.11.x

addons:
  postgresql: "9.6"

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure --vendor-only -v

services:
  - postgresql

script:
  - go test ./...
