language: go

go:
  - 1.11.x

addons:
  postgresql: "9.6"

before_install:
  - go get -tags 'postgres' -u github.com/golang-migrate/migrate/cmd/migrate
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure --vendor-only -v

services:
  - postgresql

script:
  - migrate -source file://./storage/migrations -database "postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable" up
  - go test ./...
