server:
  port: 8888
  request_timeout: 4000ms
storage:
  type: postgres
  uri: postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable
slack:
  channel_id: CG4MSSK1N
  bot_token: xoxb-548870989793-551780506195-UroDUzdUMyrbk5hyQ3lv4Kn0
