// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Approvers    string
	Commenters   string
	Idlers       string
	ProjectUsers string
	Projects     string
	PullRequests string
	Users        string
}{
	Approvers:    "approvers",
	Commenters:   "commenters",
	Idlers:       "idlers",
	ProjectUsers: "project_users",
	Projects:     "projects",
	PullRequests: "pull_requests",
	Users:        "users",
}
